### ISSUE TITLE
Error pip installation on MacOSX Cataline

### ISSUE THREAD

**Issue by nachiket** [LucaCappelletti94/pygifsicle#3]
If I try to pip install pygifsicle for python I get the following error;

```
$ sudo -H pip install pygifsicle
Collecting pygifsicle
  Downloading https://files.pythonhosted.org/packages/0c/13/1bb7b88fe584182dd0431250f0e2d54316b20c21541bf90b76876d773597/pygifsicle-1.0.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@2/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-dDt4th/pygifsicle/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-dDt4th/pygifsicle/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/tmp/pip-install-dDt4th/pygifsicle/pip-egg-info
         cwd: /private/tmp/pip-install-dDt4th/pygifsicle/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-dDt4th/pygifsicle/setup.py", line 17
        def is_stdout_enabled() -> bool:
                                ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I have also tried `sudo -H python -m pip install  pygifsicle` to the same effect.

**Comment by nachiket** [comment]
Looks like it works fine with python3

**Comment by LucaCappelletti94** [comment]
Hi, [python 2 is no longer supported](https://pythonclock.org/) nor this package ever supported or will support legacy python versions. 

I suggest you consider either updating to a python 3.x version or to directly use the gifsicle library.
