### ISSUE TITLE
FileNotFoundError: [WinError 2] Не удается найти указанный файл (The system cannot find the file specified)

### ISSUE THREAD

**Issue by belo4ya** [LucaCappelletti94/pygifsicle#5]
OS: Windows 64-bit
Python: Python 3.9.0

Hello! I try to use the optimize function and get the following error: File Not Found Error: [WinError 2] The system cannot find the file specified

The file on this path definitely exists! What could be the problem?

My code:
```
import imageio
from pygifsicle import optimize
import os

path = r"D:\PyProjects\practice\lab3\gif"
save_path = "anim.gif"

os.chdir(path)
filenames = os.listdir()
images = []

with imageio.get_writer(save_path, mode='I', fps=30) as writer:
    for filename in filenames:
        if filename.endswith(".png"):
            writer.append_data(imageio.imread(filename))

optimize(save_path)
```

Traceback:
```
Traceback (most recent call last):
  File "D:\PyProjects\practice\lab3\create_gif.py", line 17, in <module>
    optimize(save_path)
  File "D:\PyProjects\practice\lab3\venv\lib\site-packages\pygifsicle\pygifsicle.py", line 64, in optimize
    gifsicle(source, *args, **kwargs, optimize=True)
  File "D:\PyProjects\practice\lab3\venv\lib\site-packages\pygifsicle\pygifsicle.py", line 52, in gifsicle
    subprocess.call(["gifsicle", *options, *sources, "--colors",
  File "C:\Users\super\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\super\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\super\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Не удается найти указанный файл
```

**Comment by belo4ya** [comment]
Sorry, it turns out this issue has already been raised. My problem was that I didn't install Gifsicle.
